### ISSUE TITLE
Bluetooth consumption wrong values in battery stats

### ISSUE THREAD

**Issue by Dark4Codrutz** [CyanogenMod/android_device_motorola_clark#3]
[As of build 09/10 onwards]
Even though it does work perfectly normal, the battery stats reports those absurd values. Another side note is that power_profile.xml has the correct values.
Could someone please look into it ?
If necessary I can report logcats, but I thought it wasn't necessary for this case so I didn't ...
Screenshots

> ![screenshot_20161012-074912](https://cloud.githubusercontent.com/assets/18706363/19298950/951fa464-9051-11e6-80ba-9348a4cd808d.png)
> 
> ![screenshot_20161012-074907](https://cloud.githubusercontent.com/assets/18706363/19298951/953bb3f2-9051-11e6-8287-1ab11074d9a4.png)

**Comment by Dark4Codrutz** [comment]
Update, build 22/10 still persist on misgiving the estimated power consumption!
(I have flashed everything all over again: full back to stock - clean flash CM --> ROM ISSUE!!)

**Comment by JCLemme** [comment]
I've noticed the problem on the 10/22 build as well. It might be my imagination, but Bluetooth does seem to use more battery now - not as much as is being reported, but my battery's been draining a lot faster than normal with the 10/22 build and Bluetooth enabled.

**Comment by Dark4Codrutz** [comment]
I don't have certain data, nor I had suspected anything, but to me the actual power consumption of Bluetooth seems normal (I'm using BT2.1 headphones pair). The only issue here is the estimated power consumption that is horrendously out of measure.

**Comment by byron8899** [comment]
Hello, I am also experiencing the bluetooth stats issue as well.  On the other hand,  if you leave the bluetooth unbonded or paired for a while, the battery stats will record as normal.

**Comment by Dark4Codrutz** [comment]
@byron8899 sadly for me it doesn't apply. I use Bluetooth often with my headphones and also a Chinese portable speaker, but it persists. It is reporting wrong data all the time. I haven't tried other custom Roms other than CM and AICP, where the issue exists, but I can confirm that the stock rim reports correct values.

It might be a simple coincidence (maybe a commit that happened near the same time) but I deleted some battery stats files from the system itself and after that I noticed the issue. I flashed, clean flashed and also went back to stock at least once before that, I don't believe is the actual root of the issue because going back to stock I wiped everything out..

I will try to read out all commits prior to the date from the first post to try to figure out what changed but this makes sense to do only if is a common issue and I'm not the only one being affected! (the purpose of this issue post)

Please share your experience if you read this !

**Comment by byron8899** [comment]
I remembered that the CM September nighties didn't have a bluetooth stats issue, but sadly, it is gone, so we couldn't test on that.  On the other hand, I can also confirm that when I flashed the Dirty Unicorns ROM and used it for a while with the bluetooth bonded,  the battery stats was showing the right data. 

I'm pretty sure this is the CM13 nightly issue.

**Comment by invisiblek** [comment]
Hmm, reverting this will probably fix it: https://github.com/CyanogenMod/android_device_motorola_clark/commit/efc5709bc505763255d8cdb3ca53eaa10170048c

EDIT: didn't seem to. I'll do some more digging.
EDIT2: This may do the trick, matches stock: http://review.cyanogenmod.org/#/c/170086/

**Comment by Dark4Codrutz** [comment]
Issue was fixed as of build 12th of November on AICP (I don't know the corresponding build date for CM when the commit was merged, maybe a day or too before AICP)
